version: "2"

linters:
  default: standard
  enable:
    - ineffassign
    - misspell
    - unconvert
    - unused
    - funlen
    - gocognit
  settings:
    funlen:
      lines: 100
      statements: 60
    gocognit:
      min-complexity: 20

formatters:
  enable:
    - gofmt
