package app

const docInit = `
Behavior:
  Creates the Context Baggage storage home and a machine-local device identity.
  It does not modify any target project repository.

Important:
  Run this once per machine before workspace or sync use.
`

const docStatus = `
Behavior:
  Shows machine-local device identity, the current workspace, any active task,
  detected agent inventory, and the configured sync folder.

See also:
  workspace status
  sync status
`

const docDoctor = `
Behavior:
  Checks configuration, workspace identity, and sync health.

Important:
  Some findings are warnings and still let the command succeed. Integrity
  problems (such as a path owned by more than one workspace) fail the command.
  Doctor reports problems but never auto-repairs.
`

const docDiscover = `
Behavior:
  Reads known coding-agent configuration for the supported adapters (Claude Code
  and Codex) and writes a sanitized inventory. Discovery is read-only with
  respect to the agent configuration itself.
`

const docCheckpoint = `
Behavior:
  Records a checkpoint for the active task with a message. A checkpoint is an
  append-only continuity record; it does not replace task or handoff state.

Important:
  Requires an active task in the current workspace.
`

const docHandoff = `
Behavior:
  Shows the current task's handoff file, creating it with a template when it does
  not yet exist. It is not generated by an AI and does not summarize anything
  automatically.
`

const docMan = `
Usage (nested):
  ctx-bag man workspace attach

Behavior:
  The manual is built into the binary and always matches the installed version.

Important:
  Topics are matched exactly. An unknown topic returns an error and exits with a
  non-zero status, and extra tokens are not silently ignored.
`
